apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: {{ .Chart.Name }}-role
  namespace: {{ .Release-Namespace }}
rules:
  - apiGroups:
      [
        "",
        "apps",
        "rbac.authorization.k8s.io",
        "roles.rbac.authorization.k8s.io",
        "authorization.k8s.io",
      ]
    #
    # at the HTTP level, the name of the resource for accessing Secret
    # objects is "secrets"
    resources: ["deployments"]
    verbs: ["get", "watch", "list", "create", "delete"]
